apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: gpu-npd
  namespace: gpu-npd-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: gpu-node-problem-detector
    version: v0.0.3
spec:
  selector:
    matchLabels:
      k8s-app: gpu-node-problem-detector
  template:
    metadata:
      labels:
        k8s-app: gpu-node-problem-detector
    spec:
      volumes:
        - name: localtime
          hostPath:
            path: /etc/localtime
            type: FileOrCreate
        - name: run-nvidia
          hostPath:
              path: /run/nvidia
              type: ''
      # initContainers:
      #   - name: toolkit-validation
      #     image: nvcr.io/nvidia/cloud-native/gpu-operator-validator:v23.9.1
      #     command:
      #       - sh
      #       - '-c'
      #     args:
      #       - >-
      #         until [ -f /run/nvidia/validations/toolkit-ready ]; do echo waiting
      #         for nvidia container stack to be setup; sleep 5; done
      #     resources: { }
      #     volumeMounts:
      #       - name: run-nvidia
      #         mountPath: /run/nvidia
      #         mountPropagation: HostToContainer
      #     terminationMessagePath: /dev/termination-log
      #     terminationMessagePolicy: File
      #     imagePullPolicy: IfNotPresent
      containers:
        - name: node-problem-detector
          image: >-
            bpopov/gpu-node-problem-detector@sha256:e8ab8e24c3c709b048e6642c0ff93e6d4580258c4f1f0a9705de419bbe4f594e
          command:
            - /bin/sh
            - '-c'
            - >-
              exec /node-problem-detector --logtostderr --v=2
              --config.custom-plugin-monitor=/config/nvidia-smi-config.json
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 20m
              memory: 200Mi
          volumeMounts:
            - name: localtime
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        nvidia.com/gpu.present: 'true'
      serviceAccountName: gpu-npd
      securityContext: {}
      schedulerName: default-scheduler
      tolerations:
        - operator: Exists
          effect: NoExecute
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoSchedule
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  revisionHistoryLimit: 10