---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-npd
  namespace: gpu-npd-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-npd
  namespace: gpu-npd-system
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - patch
    apiGroups:
      - ''
    resources:
      - nodes/status
  - verbs:
      - create
      - patch
      - update
    apiGroups:
      - ''
      - events.k8s.io
    resources:
      - events

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-npd-binding
  namespace: gpu-npd-system
subjects:
  - kind: ServiceAccount
    name: gpu-npd
    namespace: gpu-npd-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpu-npd
