apiVersion: batch/v1
kind: Job
metadata:
  name: kubeflow-uninstall-job
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: pre-delete
          image: {{ include "kubeflow_installer.image" . | quote }}
          command: [ "bash", "/scripts/delete-script.sh" ]
          volumeMounts:
            - name: script-volume
              mountPath: "/scripts"
              readOnly: true
          securityContext:
            runAsUser: 0
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: kubeflow-scripts-configmap
            defaultMode: 0777 # This is to ensure the script is executable
      serviceAccountName: kubectl-access
