apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-storage-credentials
type: Opaque
data:
  access_key: {{ .Values.accessKey | b64enc}}
  secret_key: {{ .Values.secretKey | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: kubeflow-app-of-apps
type: Opaque
data:
  app-of-apps.yaml: {{ include "chart.app-of-apps" . | b64enc | quote }}
