apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
      - name: host-volume
        mountPath: /shared
  volumes:
    - name: host-volume
      hostPath:
        path: /shared
        type: Directory