apiVersion: v1
kind: Pod
metadata:
  name: cuda-vector-add
spec:
  restartPolicy: OnFailure
  tolerations:
  - key: group
    operator: Equal
    value: a100-gpu
    effect: NoSchedule
  containers:
    - name: cuda-vector-add
      # https://github.com/kubernetes/kubernetes/blob/v1.7.11/test/images/nvidia-cuda/Dockerfile
      image: "reg.xpkg.ru/library/cuda-vector-add:v0.1"
      resources:
        limits:
          nvidia.com/gpu: 1 # Запрос 1 GPU.

